const express = require("express");
const { protect, requireRole } = require("../middleware/authMiddleware");
const c = require("../controllers/aptitudeController");

const router = express.Router();
router.use(protect, requireRole("student"));
router.get("/dashboard", c.getDashboard);
router.get("/topics", c.getTopics);
router.get("/analytics", c.getAnalytics);
router.get("/mistakes", c.getMistakes);
router.get("/skill-dna", c.getSkillDNA);
router.get("/speed-accuracy", c.getSpeedAccuracy);
router.get("/confidence-calibration", c.getConfidenceCalibration);
router.get("/revision", c.getRevision);
router.get("/readiness-breakdown", c.getReadinessBreakdown);
router.get("/streak-calendar", c.getStreakCalendar);
router.get("/companies", c.getCompanies);
router.post("/practice/revision", c.startRevisionPractice);
router.post("/practice/fix-mistakes", c.fixMistakes);
router.post("/practice/mistake-replay", c.startMistakeReplay);
router.get("/recommendations", c.getRecommendations);
router.get("/daily-mission", c.getDailyMission);
router.get("/badges", c.getBadges);
router.get("/questions", c.getQuestions);
router.get("/questions/:id", c.getQuestion);
router.get("/questions/:questionId/similar", c.getSimilarQuestion);
router.post("/attempts", c.submitAttempt);
router.post("/sessions", c.createSession);
router.post("/sessions/company", c.createCompanySession);
// Backward-compatible alias for older frontend bundles.
router.get("/sessions", c.getActiveSession);
router.get("/sessions/active", c.getActiveSession);
router.get("/sessions/:id/review", c.getSessionReview);
router.post("/sessions/:id/repractice-mistakes", c.repracticeSessionMistakes);
router.get("/sessions/:id", c.getSession);
router.post("/sessions/:id/submit", c.submitSession);
router.post("/sessions/mark-review", c.markForReview);
router.get("/bookmarks", c.getBookmarks);
router.post("/questions/:questionId/bookmark", c.toggleBookmark);
router.post("/questions/:questionId/report", c.reportQuestion);
module.exports = router;
