import React, { useEffect, useMemo, useState } from 'react';
import { useParams } from 'react-router-dom';
import { Plus, Flag, Calendar } from 'lucide-react';
import { createTask, getTasks, updateTask } from '../frontend/src/features/study-groups-gemini/api';

const columns = [
  { id: 'TODO', title: 'To Do', color: 'bg-gray-400' },
  { id: 'IN_PROGRESS', title: 'In Progress', color: 'bg-blue-500' },
  { id: 'DONE', title: 'Done', color: 'bg-green-500' },
];
const priorityStyles = { High: 'bg-red-100 text-red-800', Medium: 'bg-yellow-100 text-yellow-800', Low: 'bg-green-100 text-green-800' };

const Avatar = ({ user }) => <div className="h-6 w-6 rounded-full bg-gray-200 flex items-center justify-center text-xs font-bold text-gray-600" title={user.name}>{(user.name || 'M').charAt(0)}</div>;
const TaskCard = ({ task }) => <div className="bg-white p-3 rounded-lg shadow-sm border border-gray-200 mb-3"><p className="text-sm font-medium text-gray-800">{task.title}</p><div className="flex items-center flex-wrap gap-x-3 gap-y-1 text-xs text-gray-500 mt-3">{task.priority && <span className={`flex items-center gap-1 px-2 py-0.5 rounded-md ${priorityStyles[task.priority]}`}><Flag size={12} /> {task.priority}</span>}{task.dueDate && <span className="flex items-center gap-1"><Calendar size={12} /> {new Date(task.dueDate).toLocaleDateString('en-US', { month: 'short', day: 'numeric' })}</span>}</div>{!!task.assignedTo?.length && <div className="flex justify-end mt-3"><div className="flex -space-x-2">{task.assignedTo.map((user) => <Avatar key={user._id} user={user} />)}</div></div>}</div>;

const StudyGroupTasksPage = () => {
  const { groupId } = useParams();
  const [tasks, setTasks] = useState([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [showForm, setShowForm] = useState(false); const [error, setError] = useState('');
  const [form, setForm] = useState({ title: '', priority: 'Medium', dueDate: '' });
  const loadTasks = async () => { if (!groupId) return; setLoading(true); try { setTasks(await getTasks(groupId)); setError(''); } catch (err) { setError(err.response?.data?.message || 'Tasks could not be loaded.'); } finally { setLoading(false); } };
  useEffect(() => { loadTasks(); }, [groupId]);
  const tasksByColumn = useMemo(() => columns.reduce((result, column) => { result[column.id] = tasks.filter((task) => task.status === column.id); return result; }, {}), [tasks]);
  const submit = async (event) => { event.preventDefault(); if (!form.title.trim()) return; setSaving(true); try { const task = await createTask(groupId, form); setTasks((current) => [task, ...current]); setForm({ title: '', priority: 'Medium', dueDate: '' }); setShowForm(false); setError(''); } catch (err) { setError(err.response?.data?.message || 'Task could not be created.'); } finally { setSaving(false); } };
  const changeStatus = async (task, status) => { try { const updated = await updateTask(groupId, task._id, { status }); setTasks((current) => current.map((item) => item._id === updated._id ? updated : item)); } catch (err) { setError(err.response?.data?.message || 'Task could not be updated.'); } };
  const completedTasks = tasksByColumn.DONE?.length || 0; const progress = tasks.length ? Math.round((completedTasks / tasks.length) * 100) : 0;
  return <div className="space-y-6"><div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4"><div><h1 className="text-2xl font-bold text-gray-900">Tasks & Goals</h1><p className="text-sm text-gray-600 mt-1">Organize and track your group's objectives.</p></div><button type="button" onClick={() => setShowForm((current) => !current)} className="flex items-center gap-2 bg-blue-500 text-white px-4 py-2 rounded-lg hover:bg-blue-600 transition-colors shadow-sm"><Plus size={18} /><span>Create Task</span></button></div>
    {showForm && <form onSubmit={submit} className="bg-white p-4 rounded-lg shadow-sm border border-gray-200 flex flex-col md:flex-row gap-3"><input required value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} className="flex-1 border rounded-lg px-3 py-2" placeholder="Task title" /><select value={form.priority} onChange={(event) => setForm({ ...form, priority: event.target.value })} className="border rounded-lg px-3 py-2"><option>Low</option><option>Medium</option><option>High</option></select><input type="date" value={form.dueDate} onChange={(event) => setForm({ ...form, dueDate: event.target.value })} className="border rounded-lg px-3 py-2" /><button disabled={saving} className="bg-blue-500 text-white rounded-lg px-4 py-2">{saving ? 'Saving…' : 'Save task'}</button></form>}
    {error && <div className="bg-red-50 text-red-700 border border-red-200 rounded-lg px-4 py-3">{error}<button type="button" className="ml-3 underline" onClick={loadTasks}>Retry</button></div>}
    <div className="bg-white p-4 rounded-lg shadow-sm border border-gray-200"><div className="flex justify-between items-center mb-2"><h3 className="text-md font-semibold text-gray-800">Group Progress</h3><span className="text-lg font-bold text-gray-900">{progress}%</span></div><div className="w-full bg-gray-200 rounded-full h-2.5"><div className="bg-green-500 h-2.5 rounded-full transition-all duration-500" style={{ width: `${progress}%` }} /></div><p className="text-xs text-gray-500 mt-2 text-right">{completedTasks} of {tasks.length} tasks completed</p></div>
    {loading ? <div className="bg-white rounded-lg border p-8 text-center text-gray-500">Loading tasks…</div> : <div className="flex flex-col md:flex-row gap-5 overflow-x-auto pb-4">{columns.map((column) => <div key={column.id} className="bg-gray-50 rounded-xl p-3 w-full md:w-1/3 flex-shrink-0"><div className="flex justify-between items-center mb-4 px-1"><div className="flex items-center gap-2"><div className={`w-2.5 h-2.5 rounded-full ${column.color}`} /><h3 className="font-semibold text-gray-700">{column.title}</h3></div><span className="text-sm font-medium text-gray-500 bg-gray-200 rounded-full px-2 py-0.5">{tasksByColumn[column.id].length}</span></div>{tasksByColumn[column.id].map((task) => <div key={task._id}><TaskCard task={task} /><select value={task.status} onChange={(event) => changeStatus(task, event.target.value)} className="mb-3 border rounded px-2 py-1 text-xs" aria-label={`Status for ${task.title}`}><option value="TODO">To Do</option><option value="IN_PROGRESS">In Progress</option><option value="DONE">Done</option></select></div>)}{!tasksByColumn[column.id].length && <div className="text-center py-10 border-2 border-dashed border-gray-200 rounded-lg"><p className="text-sm text-gray-500">No tasks here</p></div>}</div>)}</div>}
  </div>;
};
export default StudyGroupTasksPage;
