import api from "../../api/api";

const base = "/api/study-groups";
export const getGroups = (params = {}) => api.get(base, { params }).then((r) => r.data);
export const getMyGroups = () => api.get(`${base}/my`).then((r) => r.data);
export const createGroup = (payload) => api.post(base, payload).then((r) => r.data);
export const createInviteLink = (id) => api.post(`${base}/${id}/invite-link`).then((r) => r.data);
export const getInvite = (token) => api.get(`${base}/invite/${token}`).then((r) => r.data);
export const acceptInvite = (token) => api.post(`${base}/invite/${token}/accept`).then((r) => r.data);
export const getDashboard = (id) => api.get(`${base}/${id}/dashboard`).then((r) => r.data);
export const getMembers = (id) => api.get(`${base}/${id || window.location.pathname.split('/').pop()}/members`).then((r) => r.data);
export const getJoinRequests = (id) => api.get(`${base}/${id}/requests`).then((r) => r.data);
export const approveJoinRequest = (groupId, memberId) => api.patch(`${base}/${groupId}/members/${memberId}/approve`).then((r) => r.data);
export const removeGroupMember = (groupId, memberId) => api.delete(`${base}/${groupId}/members/${memberId}`).then((r) => r.data);
export const getGroup = (id) => api.get(`${base}/${id}`).then((r) => r.data);
export const updateGroupAppearance = (id, payload) => api.patch(`${base}/${id}`, payload).then((r) => r.data);
export const joinGroup = (id) => api.post(`${base}/${id}/join`).then((r) => r.data);
export const leaveGroup = (id) => api.post(`${base}/${id}/leave`).then((r) => r.data);
export const requestToJoin = (id) => api.post(`${base}/${id}/join`).then((r) => r.data);
export const getMessages = (id, before) => api.get(`${base}/${id}/messages`, { params: before ? { before } : {} }).then((r) => r.data);
export const sendMessage = (id, content) => api.post(`${base}/${id}/messages`, { content }).then((r) => r.data);
export const markGroupMessageNotificationsRead = (id) => api.post(`/api/notifications/group/${id}/messages/read`).then((r) => r.data);
export const getCompetitiveTests = (groupId, page = 1, limit = 10) => api.get(`${base}/${groupId}/competitive-tests`, { params: { page, limit } }).then((r) => r.data);
export const createCompetitiveTest = (groupId, payload) => api.post(`${base}/${groupId}/competitive-tests`, payload).then((r) => r.data);
export const joinCompetitiveTest = (groupId, testId) => api.post(`${base}/${groupId}/competitive-tests/${testId}/join`).then((r) => r.data);
export const startCompetitiveTest = (groupId, testId) => api.post(`${base}/${groupId}/competitive-tests/${testId}/start`).then((r) => r.data);
export const getCompetitiveTest = (groupId, testId) => api.get(`${base}/${groupId}/competitive-tests/${testId}`).then((r) => r.data);
export const createCompetitiveAptitudeSession = (groupId, testId) => api.post(`${base}/${groupId}/competitive-tests/${testId}/aptitude-session`).then((r) => r.data);
export const getCompetitiveResults = (groupId, testId) => api.get(`${base}/${groupId}/competitive-tests/${testId}/results`).then((r) => r.data);
export const getCompetitiveAttemptSubmissions = (groupId, testId, attemptId) => api.get(`${base}/${groupId}/competitive-tests/${testId}/attempts/${attemptId}/submissions`).then((r) => r.data);
