import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { createGroup, createInviteLink } from "./api";
import "./studyGroups.css";
import "./studyGroupsApp.css";
import "./studyGroupsWorkspace.css";

export default function StudyGroupCreatePage() {
  const navigate = useNavigate(); const [step, setStep] = useState(1); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [created, setCreated] = useState(null); const [inviteUrl, setInviteUrl] = useState(""); const [copied, setCopied] = useState(false); const [form, setForm] = useState({ name: "", topic: "", description: "", goal: "", isPublic: true }); const update = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  const submit = async (event) => { event.preventDefault(); setSaving(true); setError(""); try { const group = await createGroup(form); const invite = await createInviteLink(group._id); setCreated(group); setInviteUrl(invite.inviteUrl); } catch (err) { setError(err.response?.data?.message || "Could not create the group. Try again."); } finally { setSaving(false); } };
  const copy = async () => { try { await navigator.clipboard.writeText(inviteUrl); setCopied(true); setTimeout(() => setCopied(false), 1800); } catch { setError("Copy failed. Select and copy the invite link manually."); } };
  if (created) return <main className="sg-app"><div className="sg-main"><section className="sg-card sg-success-card"><span className="sg-eyebrow">GROUP CREATED</span><h1 className="sg-title">Invite your study partners</h1><p className="sg-sub">Your group is ready. Share this private invite link with the people you want to study with.</p><label className="sg-field"><span>INVITE LINK · EXPIRES IN 7 DAYS</span><input readOnly value={inviteUrl} onFocus={(event) => event.target.select()} /></label><div className="sg-actions"><button className="sg-btn accent" type="button" onClick={copy}>{copied ? "Copied ✓" : "Copy invite link"}</button><button className="sg-btn" type="button" onClick={() => navigate(`/dashboard/groups/${created._id}`)}>Open group</button></div><p className="sg-muted" style={{ marginTop: 16 }}>Anyone with this link must be signed in to join.</p></section></div></main>;
  return <main className="sg-app"><div className="sg-main"><Link to="/dashboard/groups" className="sg-muted">← Back to Study Groups</Link><div className="sg-top" style={{ marginTop: 22 }}><div><div className="sg-eyebrow">New workspace</div><h1 className="sg-title">Create a study group</h1><p className="sg-sub">Give your group a clear purpose and start learning together.</p></div><span className="sg-chip">Step {step} of 3</span></div><form className="sg-card sg-form" onSubmit={submit}>{step === 1 && <><h2>Group basics</h2><div className="sg-field"><label>GROUP NAME</label><input required minLength="3" maxLength="100" value={form.name} onChange={(event) => update("name", event.target.value)} placeholder="e.g. System Design Collective" /></div><div className="sg-field"><label>CATEGORY</label><input required value={form.topic} onChange={(event) => update("topic", event.target.value)} placeholder="DSA, frontend, system design…" /></div><div className="sg-field"><label>DESCRIPTION</label><textarea required rows="4" maxLength="500" value={form.description} onChange={(event) => update("description", event.target.value)} placeholder="What will members learn together?" /></div></>}{step === 2 && <><h2>Learning goal</h2><div className="sg-field"><label>WEEKLY GOAL</label><input value={form.goal} onChange={(event) => update("goal", event.target.value)} placeholder="e.g. Solve 20 problems together" /></div><p className="sg-muted">You can refine goals as the group grows.</p></>}{step === 3 && <><h2>Privacy</h2><label className="sg-row" style={{ border: 0, padding: 0 }}><input type="checkbox" checked={form.isPublic} onChange={(event) => update("isPublic", event.target.checked)} /><span><strong>Public group</strong><p>Anyone can discover and join this group.</p></span></label><div className="sg-card"><small>READY TO CREATE</small><h3>{form.name || "Your new group"}</h3><p>{form.description || "Your group description will appear here."}</p></div></>}{error && <p style={{ color: "var(--red)" }}>{error}</p>}<div className="sg-actions" style={{ justifyContent: "space-between" }}><button type="button" className="sg-btn" disabled={step === 1} onClick={() => setStep((value) => value - 1)}>Back</button>{step < 3 ? <button type="button" className="sg-btn accent" disabled={step === 1 && !form.name} onClick={() => setStep((value) => value + 1)}>Continue →</button> : <button className="sg-btn accent" disabled={saving}>{saving ? "Creating…" : "Create group →"}</button>}</div></form></div></main>;
}
