import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { acceptInvite, getGroup, getInvite, joinGroup } from "./api";
import "./studyGroups.css";
import "./studyGroupsApp.css";
import "./studyGroupsWorkspace.css";

function readInviteToken(value) { const match = value.match(/\/invite\/([^/?#]+)/i); return match?.[1] || (value.length > 20 && !/^[a-f0-9]{24}$/i.test(value) ? value.trim() : ""); }

export default function StudyGroupJoinPage() { const navigate = useNavigate(); const [value, setValue] = useState(""); const [preview, setPreview] = useState(null); const [inviteToken, setInviteToken] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false); const [joining, setJoining] = useState(false); const previewGroup = async (event) => { event.preventDefault(); setError(""); setPreview(null); setInviteToken(""); setLoading(true); try { const token = readInviteToken(value.trim()); if (token) { const result = await getInvite(token); setPreview(result.group); setInviteToken(token); } else { setPreview(await getGroup(value.trim())); } } catch (err) { setError(err.response?.data?.message || "We could not find this group or invite link."); } finally { setLoading(false); } }; const join = async () => { setJoining(true); setError(""); try { const result = inviteToken ? await acceptInvite(inviteToken) : await joinGroup(preview._id); navigate(`/dashboard/groups/${result.group?._id || preview._id}`); } catch (err) { setError(err.response?.data?.message || "Could not join this group."); } finally { setJoining(false); } }; return <main className="sg-app"><div className="sg-main"><Link to="/dashboard/groups" className="sg-muted">← Back to Study Groups</Link><div className="sg-invite-card"><span className="sg-eyebrow">JOIN YOUR CIRCLE</span><h1 className="sg-title">Join a Study Group</h1><p className="sg-sub">Paste a group ID or the complete invite link. Preview it first, then join with one click.</p><form className="sg-card sg-form" onSubmit={previewGroup}><div className="sg-field"><label>GROUP ID OR INVITE LINK</label><input required value={value} onChange={(event) => setValue(event.target.value)} placeholder="Paste the invite link here" /></div><button className="sg-btn primary" disabled={loading}>{loading ? "Checking…" : "Preview group"}</button>{error && <p style={{ color: "var(--red)" }}>{error}</p>}</form>{preview && <section className="sg-card" style={{ marginTop: 16 }}><div className="sg-cover"><span className="sg-avatar">{preview.name?.[0] || "S"}</span></div><span className="sg-chip">{preview.topic || "Study group"}</span><h2 style={{ marginTop: 12 }}>{preview.name}</h2><p>{preview.description || "Learn and practice together with this group."}</p><div className="sg-meta"><span>{preview.isPublic ? "Public group" : "Invite access"}</span></div><button type="button" className="sg-btn accent" style={{ marginTop: 18 }} disabled={joining} onClick={join}>{joining ? "Joining…" : "Join group →"}</button></section>}</div></div></main>; }
