require("dotenv").config({ path: require("path").join(__dirname, "../.env") });
const mongoose = require("mongoose");
const crypto = require("crypto");
const AptitudeQuestion = require("../models/AptitudeQuestion");

const hash = (text) => crypto.createHash("sha256").update(text.trim().toLowerCase().replace(/\s+/g, " ")).digest("hex").slice(0, 16);
const question = ({ text, A, B, C, D, correct, explanation, shortTrick = "", conceptNote = "", category, topic, difficulty, expectedTime = 45, tags = [] }) => ({
  question: text,
  options: [{ key: "A", text: A }, { key: "B", text: B }, { key: "C", text: C }, { key: "D", text: D }],
  correctAnswer: correct,
  explanation,
  shortTrick,
  conceptNote,
  category,
  topic,
  difficulty,
  expectedTime,
  tags,
  sourceType: "CODEVERSE_ORIGINAL",
  sourceReference: "CodeVerse Original Aptitude v2",
  qualityStatus: "PUBLISHED",
  contentHash: hash(text),
});

const QUESTIONS = [
  // ---------- Quantitative Aptitude (17) ----------
  question({ text: "Find the remainder when 7^100 is divided by 5.", A: "1", B: "2", C: "3", D: "4", correct: "A", explanation: "Powers of 7 mod 5 cycle as 2, 4, 3, 1 repeating every 4 steps. 100 is a multiple of 4, so the remainder is 1.", shortTrick: "For remainder-of-power problems, find the cycle length of the base modulo the divisor, then reduce the exponent using that cycle.", conceptNote: "Cyclicity of remainders is the fast way to handle large exponents without computing the full power.", category: "Quantitative Aptitude", topic: "Number System", difficulty: "Medium", tags: ["remainders", "cyclicity"] }),
  question({ text: "In an election between two candidates, the winner gets 60% of the valid votes and wins by 720 votes. What is the total number of valid votes?", A: "3000", B: "3200", C: "3600", D: "4000", correct: "C", explanation: "The winning margin is 60% - 40% = 20% of the total valid votes, and this equals 720. So total votes = 720 / 0.20 = 3600.", shortTrick: "In two-candidate elections, margin % = (winner % - loser %); divide the actual margin by this percentage to get the total.", category: "Quantitative Aptitude", topic: "Percentages", difficulty: "Medium", tags: ["elections"] }),
  question({ text: "A trader marks his goods 50% above the cost price and then allows two successive discounts of 20% and 10%. What is his overall profit percentage?", A: "6%", B: "8%", C: "10%", D: "12%", correct: "B", explanation: "Taking cost price as 100: marked price = 150. After a 20% discount it becomes 120, and after a further 10% discount it becomes 108. So profit is 8%.", shortTrick: "Chain successive percentage changes by multiplying factors: 1.5 x 0.8 x 0.9 = 1.08, giving 8% profit directly.", category: "Quantitative Aptitude", topic: "Profit & Loss", difficulty: "Medium", tags: ["successive discount"] }),
  question({ text: "Two numbers are in the ratio 3:5 and their sum is 96. What is the larger number?", A: "48", B: "54", C: "60", D: "66", correct: "C", explanation: "Let the numbers be 3x and 5x. Then 3x + 5x = 96, so x = 12. The larger number is 5x = 60.", category: "Quantitative Aptitude", topic: "Ratio & Proportion", difficulty: "Easy" }),
  question({ text: "The average age of a class of 30 students is 12 years. When the class teacher's age is included, the average becomes approximately 12.9 years. What is the teacher's age?", A: "36", B: "38", C: "40", D: "42", correct: "C", explanation: "Original total age = 30 x 12 = 360. With the teacher, total students become 31 with average 12.9, so new total = 31 x 12.9 ≈ 400. Teacher's age = 400 - 360 = 40.", category: "Quantitative Aptitude", topic: "Average", difficulty: "Medium" }),
  question({ text: "A can complete a task in 15 days and B can complete it in 10 days. They work together for 3 days, after which A leaves. How many more days does B alone need to finish the work?", A: "4", B: "5", C: "6", D: "7", correct: "B", explanation: "Combined 1-day rate = 1/15 + 1/10 = 1/6. In 3 days they finish 3/6 = 1/2 of the work, leaving 1/2. B alone needs (1/2) / (1/10) = 5 days.", shortTrick: "Convert every rate to 'work per day' as a fraction of the whole job, then add and subtract fractions directly.", category: "Quantitative Aptitude", topic: "Time & Work", difficulty: "Medium", tags: ["work rate"] }),
  question({ text: "Pipe A can fill a tank in 6 hours and pipe B can empty it in 8 hours. If both pipes are opened together, how long will it take to fill the tank?", A: "20 hours", B: "22 hours", C: "24 hours", D: "26 hours", correct: "C", explanation: "Net rate = 1/6 - 1/8 = (4 - 3)/24 = 1/24 of the tank per hour, so the tank fills in 24 hours.", category: "Quantitative Aptitude", topic: "Pipes & Cisterns", difficulty: "Medium" }),
  question({ text: "A man covers a distance of 300 km in 5 hours at a certain speed. If his speed is increased by 20%, how long will he take to cover the same distance?", A: "4 hours", B: "4 hours 10 minutes", C: "4 hours 20 minutes", D: "4 hours 30 minutes", correct: "B", explanation: "Original speed = 300/5 = 60 km/h. New speed = 60 x 1.2 = 72 km/h. New time = 300/72 = 25/6 hours = 4 hours 10 minutes.", category: "Quantitative Aptitude", topic: "Time Speed Distance", difficulty: "Medium" }),
  question({ text: "A boat's speed in still water is 10 km/h and the speed of the stream is 2 km/h. How long will it take to travel 24 km downstream?", A: "1.5 hours", B: "2 hours", C: "2.5 hours", D: "3 hours", correct: "B", explanation: "Downstream speed = 10 + 2 = 12 km/h. Time = 24/12 = 2 hours.", category: "Quantitative Aptitude", topic: "Boats & Streams", difficulty: "Easy" }),
  question({ text: "A sum of money doubles itself in 8 years at simple interest. What is the annual rate of interest?", A: "10%", B: "12%", C: "12.5%", D: "15%", correct: "C", explanation: "If the sum doubles, the simple interest earned equals the principal itself. Rate = (100 x P) / (P x 8) = 12.5%.", shortTrick: "For simple interest doubling in n years, rate = 100/n percent.", category: "Quantitative Aptitude", topic: "Simple Interest", difficulty: "Medium" }),
  question({ text: "Find the compound interest on Rs. 10,000 for 2 years at 10% per annum, compounded annually.", A: "Rs. 2,000", B: "Rs. 2,050", C: "Rs. 2,100", D: "Rs. 2,200", correct: "C", explanation: "Amount = 10000 x (1.1)^2 = 10000 x 1.21 = 12,100. CI = 12,100 - 10,000 = 2,100.", category: "Quantitative Aptitude", topic: "Compound Interest", difficulty: "Medium" }),
  question({ text: "In what ratio should tea worth Rs. 60/kg be mixed with tea worth Rs. 80/kg to get a mixture worth Rs. 65/kg?", A: "1:3", B: "3:1", C: "2:1", D: "1:2", correct: "B", explanation: "By the rule of alligation, ratio of cheaper to dearer = (80 - 65) : (65 - 60) = 15 : 5 = 3 : 1.", shortTrick: "Alligation rule: cheaper : dearer = (dearer price - mean price) : (mean price - cheaper price).", conceptNote: "Alligation is a fast shortcut for weighted-average mixture problems, avoiding the need to set up equations.", category: "Quantitative Aptitude", topic: "Mixture & Alligation", difficulty: "Medium" }),
  question({ text: "A bag contains 4 red and 6 blue balls. Two balls are drawn at random. What is the probability that both are red?", A: "2/15", B: "4/15", C: "1/5", D: "2/9", correct: "A", explanation: "Ways to choose 2 red from 4 = C(4,2) = 6. Total ways to choose 2 from 10 = C(10,2) = 45. Probability = 6/45 = 2/15.", category: "Quantitative Aptitude", topic: "Probability", difficulty: "Medium" }),
  question({ text: "In how many ways can the letters of the word 'TABLE' be arranged so that the vowels always come together?", A: "24", B: "48", C: "60", D: "120", correct: "B", explanation: "Treat the vowels A and E as one unit, giving 4 units to arrange (4! = 24 ways). The 2 vowels can arrange among themselves in 2! = 2 ways. Total = 24 x 2 = 48.", shortTrick: "Whenever letters must stay together, bundle them into a single block first, arrange the blocks, then arrange the letters inside the block separately.", category: "Quantitative Aptitude", topic: "Permutation & Combination", difficulty: "Medium" }),
  question({ text: "If x + 1/x = 5, find the value of x^2 + 1/x^2.", A: "21", B: "23", C: "25", D: "27", correct: "B", explanation: "Squaring both sides: (x + 1/x)^2 = x^2 + 2 + 1/x^2 = 25. So x^2 + 1/x^2 = 25 - 2 = 23.", category: "Quantitative Aptitude", topic: "Algebra", difficulty: "Easy" }),
  question({ text: "Find the area of a right-angled triangle with base 12 cm and height 5 cm.", A: "24 cm²", B: "30 cm²", C: "36 cm²", D: "60 cm²", correct: "B", explanation: "Area of a right triangle = 1/2 x base x height = 1/2 x 12 x 5 = 30 cm².", category: "Quantitative Aptitude", topic: "Geometry", difficulty: "Easy" }),
  question({ text: "The ratio of a father's age to his son's age is 7:3. After 5 years, the ratio becomes 2:1. What is the father's present age?", A: "28", B: "35", C: "42", D: "49", correct: "B", explanation: "Let the ages be 7x and 3x. After 5 years: (7x + 5)/(3x + 5) = 2, so 7x + 5 = 6x + 10, giving x = 5. Father's present age = 7 x 5 = 35.", category: "Quantitative Aptitude", topic: "Ages", difficulty: "Medium" }),

  // ---------- Logical Reasoning (14) ----------
  question({ text: "Find the missing number in the series: 5, 11, 23, 47, ?", A: "90", B: "93", C: "95", D: "97", correct: "C", explanation: "Each term is obtained by doubling the previous term and adding 1: 5x2+1=11, 11x2+1=23, 23x2+1=47, 47x2+1=95.", category: "Logical Reasoning", topic: "Number Series", difficulty: "Medium" }),
  question({ text: "Find the next term in the series: B, D, G, K, ?", A: "N", B: "O", C: "P", D: "Q", correct: "C", explanation: "The gaps between letters increase by one each time: +2, +3, +4, +5. B(2) -> D(4) -> G(7) -> K(11) -> P(16).", category: "Logical Reasoning", topic: "Letter Series", difficulty: "Medium" }),
  question({ text: "In a certain code, 'SUN' is written as 'TVO'. How is 'MOON' written in the same code?", A: "NPQO", B: "NPPO", C: "NOOP", D: "OPQP", correct: "B", explanation: "Each letter is shifted one place forward in the alphabet: M->N, O->P, O->P, N->O, giving NPPO.", category: "Logical Reasoning", topic: "Coding-Decoding", difficulty: "Easy" }),
  question({ text: "Pointing to a photograph, a man says, 'She is the daughter of my grandfather's only son.' How is the woman related to the man, assuming the man himself is not that son?", A: "Sister", B: "Mother", C: "Daughter", D: "Cousin", correct: "A", explanation: "The grandfather's only son is the man's father. So the woman, being the father's daughter, is the man's sister.", category: "Logical Reasoning", topic: "Blood Relations", difficulty: "Medium" }),
  question({ text: "A man walks 5 km north, then 3 km east, then 5 km south. How far and in which direction is he from his starting point?", A: "3 km East", B: "3 km West", C: "8 km East", D: "5 km North", correct: "A", explanation: "The 5 km north and 5 km south cancel out, leaving only the 3 km east displacement.", category: "Logical Reasoning", topic: "Direction Sense", difficulty: "Easy" }),
  question({ text: "Statements: All pens are books. All books are tables. Conclusion: All pens are tables. Does the conclusion follow?", A: "Conclusion follows", B: "Conclusion does not follow", C: "Cannot be determined", D: "Data is insufficient", correct: "A", explanation: "Since all pens are books and all books are tables, by transitivity all pens must be tables.", category: "Logical Reasoning", topic: "Syllogism", difficulty: "Easy" }),
  question({ text: "Statement: 'Most students who study daily score well in exams.' Conclusion I: All students who score well study daily. Conclusion II: Some students who study daily score well. Which conclusion(s) follow?", A: "Only I follows", B: "Only II follows", C: "Both I and II follow", D: "Neither follows", correct: "B", explanation: "'Most' implies 'some', so Conclusion II follows directly. Conclusion I reverses the logic incorrectly and does not follow.", category: "Logical Reasoning", topic: "Statement & Conclusion", difficulty: "Medium" }),
  question({ text: "Five friends A, B, C, D and E sit in a row. B sits immediately right of A. C sits immediately right of D. D is second from the left, and E sits at one of the ends. Who sits at the leftmost position?", A: "A", B: "D", C: "E", D: "B", correct: "C", explanation: "D is at position 2 and C (immediate right of D) is at position 3. The remaining positions 1, 4, 5 go to A, B and E, with E at an end. Placing E at position 1 leaves A at 4 and B at 5, giving the order E, D, C, A, B. So E is leftmost.", category: "Logical Reasoning", topic: "Seating Arrangement", difficulty: "Hard", expectedTime: 90 }),
  question({ text: "Doctor is to Hospital as Teacher is to ?", A: "Student", B: "School", C: "Books", D: "Classroom", correct: "B", explanation: "A doctor works at a hospital, and similarly a teacher works at a school — the relationship is person-to-workplace.", category: "Logical Reasoning", topic: "Analogy", difficulty: "Easy" }),
  question({ text: "Find the odd one out.", A: "Apple", B: "Mango", C: "Potato", D: "Banana", correct: "C", explanation: "Apple, Mango and Banana are fruits, while Potato is a vegetable.", category: "Logical Reasoning", topic: "Classification", difficulty: "Easy" }),
  question({ text: "In a survey, 70 people like tea, 60 like coffee, and 30 like both. How many people like tea or coffee?", A: "90", B: "100", C: "110", D: "130", correct: "B", explanation: "Using the union formula: |Tea ∪ Coffee| = 70 + 60 - 30 = 100.", conceptNote: "For two overlapping sets, |A ∪ B| = |A| + |B| - |A ∩ B|.", category: "Logical Reasoning", topic: "Venn Diagrams", difficulty: "Easy" }),
  question({ text: "What is the value of x? Statement I: x + 5 = 12. Statement II: 2x = 14.", A: "Statement I alone is sufficient", B: "Statement II alone is sufficient", C: "Each statement alone is sufficient", D: "Neither statement is sufficient", correct: "C", explanation: "Statement I gives x = 7. Statement II also gives x = 7. Since each one independently determines x, each alone is sufficient.", category: "Logical Reasoning", topic: "Data Sufficiency", difficulty: "Medium" }),
  question({ text: "P is the brother of Q. Q is the sister of R. R is the father of S. How is P related to S?", A: "Father", B: "Uncle", C: "Brother", D: "Grandfather", correct: "B", explanation: "Since P is Q's brother and Q is R's sister, P and R are siblings. As R is S's father, P (R's sibling) is S's uncle.", category: "Logical Reasoning", topic: "Puzzles", difficulty: "Medium" }),
  question({ text: "If all Zips are Zaps, and some Zaps are Zops, which of the following must be true?", A: "All Zips are Zops", B: "Some Zips are Zops", C: "No Zips are Zops", D: "Cannot be determined", correct: "D", explanation: "The overlap between Zaps and Zops may or may not include any Zips, so no definite conclusion about Zips and Zops can be drawn from the given statements.", category: "Logical Reasoning", topic: "Logical Deduction", difficulty: "Hard" }),

  // ---------- Verbal Ability (10) ----------
  question({ text: "Choose the grammatically correct sentence.", A: "She don't like tea.", B: "She doesn't like tea.", C: "She not like tea.", D: "She do not likes tea.", correct: "B", explanation: "With a third-person singular subject ('she'), the correct auxiliary verb is 'doesn't'.", category: "Verbal Ability", topic: "Sentence Correction", difficulty: "Easy" }),
  question({ text: "Despite his ___, he failed to win the race.", A: "talent", B: "talentless", C: "talently", D: "talenting", correct: "A", explanation: "The blank needs a noun after the possessive 'his', and 'talent' is the correct noun form.", category: "Verbal Ability", topic: "Sentence Completion", difficulty: "Easy" }),
  question({ text: "Choose the word closest in meaning to 'Candid'.", A: "Honest", B: "Hidden", C: "Angry", D: "Weak", correct: "A", explanation: "'Candid' means truthful and straightforward, which is closest in meaning to 'Honest'.", category: "Verbal Ability", topic: "Synonyms", difficulty: "Easy" }),
  question({ text: "Choose the word most opposite in meaning to 'Benevolent'.", A: "Kind", B: "Malevolent", C: "Generous", D: "Charitable", correct: "B", explanation: "'Benevolent' means kind and generous; its direct opposite is 'Malevolent', meaning having ill will toward others.", category: "Verbal Ability", topic: "Antonyms", difficulty: "Easy" }),
  question({ text: "Which word means 'a place where bees are kept'?", A: "Aviary", B: "Apiary", C: "Aquarium", D: "Arboretum", correct: "B", explanation: "An 'Apiary' is a place where bees are kept for honey production. An 'Aviary' is for birds.", category: "Verbal Ability", topic: "Vocabulary", difficulty: "Medium" }),
  question({ text: "Choose the grammatically correct sentence.", A: "Each of the boys have a book.", B: "Each of the boys has a book.", C: "Each of the boy has a book.", D: "Each of boys has book.", correct: "B", explanation: "'Each' is a singular pronoun and always takes a singular verb, so 'has' is correct, not 'have'.", category: "Verbal Ability", topic: "Grammar", difficulty: "Easy" }),
  question({ text: "Identify the part of the sentence that contains a grammatical error: 'The number of students (A) / in the class (B) / are increasing (C) / every year (D).'", A: "The number of students", B: "in the class", C: "are increasing", D: "every year", correct: "C", explanation: "'The number of' is a singular subject and requires a singular verb, so it should be 'is increasing', not 'are increasing'.", category: "Verbal Ability", topic: "Error Detection", difficulty: "Medium" }),
  question({ text: "She has been living here ___ 2010.", A: "since", B: "for", C: "from", D: "during", correct: "A", explanation: "'Since' is used with a specific point in time (like a year), while 'for' is used with a duration.", category: "Verbal Ability", topic: "Fill in the Blanks", difficulty: "Easy" }),
  question({ text: "Arrange the sentences P, Q, R, S in the correct order to form a coherent paragraph. P: Then he opened the door. Q: He walked to the door. R: Finally, he stepped outside. S: He heard a knock.", A: "SQPR", B: "QSPR", C: "SPQR", D: "QPSR", correct: "A", explanation: "The logical sequence is: he hears a knock (S), walks to the door (Q), opens it (P), and finally steps outside (R).", category: "Verbal Ability", topic: "Para Jumbles", difficulty: "Medium" }),
  question({ text: "Read the passage: 'Renewable energy sources such as solar and wind are becoming cheaper every year, making them more competitive with fossil fuels.' According to the passage, why are renewable sources becoming more competitive?", A: "They are heavily subsidized", B: "Their cost is decreasing", C: "Fossil fuels have been banned", D: "Government mandates require it", correct: "B", explanation: "The passage directly states that renewable sources are 'becoming cheaper every year', which is why they are more competitive.", category: "Verbal Ability", topic: "Reading Comprehension", difficulty: "Easy" }),

  // ---------- Data Interpretation (10) ----------
  question({ text: "A company's sales (in units) over four months are: Jan – 200, Feb – 250, Mar – 300, Apr – 350. What is the percentage increase in sales from January to April?", A: "50%", B: "65%", C: "75%", D: "80%", correct: "C", explanation: "Increase = 350 - 200 = 150. Percentage increase = (150/200) x 100 = 75%.", category: "Data Interpretation", topic: "Table", difficulty: "Medium", expectedTime: 60 }),
  question({ text: "In a survey of 500 people, 220 prefer tea, 180 prefer coffee, and the rest prefer neither. What percentage of people prefer neither?", A: "15%", B: "18%", C: "20%", D: "22%", correct: "C", explanation: "People preferring neither = 500 - (220 + 180) = 100. Percentage = (100/500) x 100 = 20%.", category: "Data Interpretation", topic: "Table", difficulty: "Easy", expectedTime: 60 }),
  question({ text: "A bar graph shows a company's quarterly profits (in lakhs): Q1 – 40, Q2 – 55, Q3 – 45, Q4 – 60. What is the average quarterly profit?", A: "45 lakh", B: "48 lakh", C: "50 lakh", D: "52 lakh", correct: "C", explanation: "Average = (40 + 55 + 45 + 60) / 4 = 200 / 4 = 50 lakh.", category: "Data Interpretation", topic: "Bar Graph", difficulty: "Easy", expectedTime: 60 }),
  question({ text: "Using the same quarterly profit data (Q1 – 40, Q2 – 55, Q3 – 45, Q4 – 60 lakh), what is the percentage increase in profit from Q1 to Q4?", A: "40%", B: "45%", C: "50%", D: "55%", correct: "C", explanation: "Increase = 60 - 40 = 20. Percentage increase = (20/40) x 100 = 50%.", category: "Data Interpretation", topic: "Bar Graph", difficulty: "Medium", expectedTime: 60 }),
  question({ text: "A line graph shows a company's revenue (in crores) over five years: 2019 – 10, 2020 – 12, 2021 – 9, 2022 – 15, 2023 – 18. In which year was the year-on-year percentage growth the highest?", A: "2020", B: "2021", C: "2022", D: "2023", correct: "C", explanation: "Growth rates: 2020 = 20%, 2021 = -25%, 2022 = (15-9)/9 x 100 ≈ 66.7%, 2023 = 20%. The highest growth is in 2022.", category: "Data Interpretation", topic: "Line Graph", difficulty: "Hard", expectedTime: 90 }),
  question({ text: "A pie chart shows a family's monthly budget: Food 30%, Rent 25%, Savings 20%, Transport 15%, Others 10%. If the monthly income is Rs. 50,000, how much is spent on Rent?", A: "Rs. 10,000", B: "Rs. 12,000", C: "Rs. 12,500", D: "Rs. 15,000", correct: "C", explanation: "Amount spent on Rent = 25% of 50,000 = Rs. 12,500.", category: "Data Interpretation", topic: "Pie Chart", difficulty: "Easy", expectedTime: 60 }),
  question({ text: "Using the same budget pie chart (Food 30%, Rent 25%, Savings 20%, Transport 15%, Others 10%), what is the ratio of the amount spent on Food to the amount spent on Transport?", A: "3:2", B: "2:1", C: "3:1", D: "5:2", correct: "B", explanation: "Since both are percentages of the same total income, the ratio equals 30:15 = 2:1.", category: "Data Interpretation", topic: "Pie Chart", difficulty: "Medium", expectedTime: 60 }),
  question({ text: "A mixed graph shows a store's monthly sales (bars, in units) with profit margin (line, in %): Jan – 100 units at 10% margin, Feb – 150 units at 12% margin, Mar – 200 units at 15% margin. If each unit sells for Rs. 500, what was the profit in March?", A: "Rs. 12,000", B: "Rs. 13,500", C: "Rs. 15,000", D: "Rs. 18,000", correct: "C", explanation: "March revenue = 200 x 500 = Rs. 1,00,000. Profit = 15% of 1,00,000 = Rs. 15,000.", category: "Data Interpretation", topic: "Mixed Graph", difficulty: "Medium", expectedTime: 75 }),
  question({ text: "In a class of 60 students, 35 play cricket, 30 play football, and 10 play neither sport. How many students play both cricket and football?", A: "10", B: "12", C: "15", D: "18", correct: "C", explanation: "Students playing at least one sport = 60 - 10 = 50. Using |A ∪ B| = |A| + |B| - |A ∩ B|: 50 = 35 + 30 - both, so both = 15.", category: "Data Interpretation", topic: "Caselet", difficulty: "Medium", expectedTime: 75 }),
  question({ text: "Rahul spends 40% of his salary on rent and 30% of the remainder on groceries, saving the rest. If his salary is Rs. 40,000, how much does he save?", A: "Rs. 15,800", B: "Rs. 16,200", C: "Rs. 16,800", D: "Rs. 17,200", correct: "C", explanation: "Rent = 40% of 40,000 = 16,000, leaving 24,000. Groceries = 30% of 24,000 = 7,200. Savings = 24,000 - 7,200 = Rs. 16,800.", category: "Data Interpretation", topic: "Caselet", difficulty: "Medium", expectedTime: 75 }),
];

async function seed() {
  if (!process.env.MONGO_URI) throw new Error("MONGO_URI is missing");
  await mongoose.connect(process.env.MONGO_URI);
  let inserted = 0;
  for (const item of QUESTIONS) {
    const result = await AptitudeQuestion.updateOne({ contentHash: item.contentHash }, { $setOnInsert: item }, { upsert: true });
    if (result.upsertedCount) inserted += 1;
  }
  console.log(`Aptitude batch-2 seed complete. Inserted: ${inserted}/${QUESTIONS.length}. Total published: ${await AptitudeQuestion.countDocuments({ qualityStatus: "PUBLISHED" })}`);
  await mongoose.disconnect();
}

seed().catch(async (error) => { console.error("Aptitude batch-2 seed failed:", error.message); await mongoose.disconnect().catch(() => {}); process.exitCode = 1; });
