import { useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { Calendar, Link2, Plus, Users, Video, X } from "lucide-react";
import api from "../../api/api";
import { getRealtimeSocket } from "../../realtime/socket";
import { cancelMockInterview, createMockInterview, listMockInterviews } from "./api";
import "./mockInterviews.css";

const formatWhen = (value) => new Date(value).toLocaleString(undefined, { weekday: "short", month: "short", day: "numeric", hour: "numeric", minute: "2-digit" });

function ScheduleModal({ onClose, onCreated }) {
  const [title, setTitle] = useState(""); const [scheduledAt, setScheduledAt] = useState(""); const [durationMinutes, setDurationMinutes] = useState(45); const [query, setQuery] = useState(""); const [results, setResults] = useState([]); const [invited, setInvited] = useState([]); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { const q = query.trim(); if (q.length < 2) { setResults([]); return undefined; } let active = true; const timer = setTimeout(() => api.get("/api/direct-messages/search", { params: { query: q } }).then((r) => active && setResults(r.data.users || [])).catch(() => { if (active) setResults([]); }), 250); return () => { active = false; clearTimeout(timer); }; }, [query]);
  const submit = async (event) => { event.preventDefault(); setError(""); if (!title.trim() || !scheduledAt) return setError("Title and date/time are required"); setSaving(true); try { await onCreated(await createMockInterview({ title: title.trim(), scheduledAt: new Date(scheduledAt).toISOString(), durationMinutes, participantIds: invited.map((u) => u.id) })); } catch (e) { setError(e.response?.data?.message || "Could not schedule the interview"); } finally { setSaving(false); } };
  return <div className="mi-backdrop" role="dialog" aria-modal="true"><form className="mi-modal" onSubmit={submit}><header><h2>Schedule a mock interview</h2><button type="button" className="mi-icon-btn" onClick={onClose} aria-label="Close"><X size={17} /></button></header><label className="mi-field"><span>Title</span><input value={title} onChange={(e) => setTitle(e.target.value)} maxLength={120} placeholder="e.g. DSA mock — arrays & recursion" /></label><div className="mi-field-row"><label className="mi-field"><span>Date &amp; time</span><input type="datetime-local" value={scheduledAt} onChange={(e) => setScheduledAt(e.target.value)} /></label><label className="mi-field mi-field-narrow"><span>Duration</span><select value={durationMinutes} onChange={(e) => setDurationMinutes(Number(e.target.value))}><option value={30}>30 min</option><option value={45}>45 min</option><option value={60}>60 min</option><option value={90}>90 min</option><option value={120}>120 min</option></select></label></div><label className="mi-field"><span>Invite people (optional)</span><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search by name or username" /></label>{results.length > 0 && <ul className="mi-search-results">{results.map((u) => <li key={u.id}><button type="button" onClick={() => { if (!invited.some((x) => x.id === u.id)) setInvited([...invited, u]); setQuery(""); setResults([]); }}>{u.name} <small>@{u.username}</small></button></li>)}</ul>}{invited.length > 0 && <div className="mi-invited-chips">{invited.map((u) => <span className="mi-chip" key={u.id}>{u.name}<button type="button" onClick={() => setInvited(invited.filter((x) => x.id !== u.id))} aria-label={`Remove ${u.name}`}><X size={12} /></button></span>)}</div>}{error && <div className="mi-error">{error}</div>}<footer><button type="button" className="mi-btn-ghost" onClick={onClose}>Cancel</button><button className="mi-btn-primary" disabled={saving}>{saving ? "Scheduling…" : "Schedule interview"}</button></footer></form></div>;
}

  function InterviewCard({ interview, onCancel, onEnter }) { const [copied, setCopied] = useState(false); const link = `${window.location.origin}/dashboard/mock/join/${interview.joinCode}`; const canJoin = interview.status === "LIVE" || (interview.status === "SCHEDULED" && new Date(interview.scheduledAt).getTime() - Date.now() < 5 * 60000); return <article className={`mi-card mi-card-${interview.status.toLowerCase()}`}><div><h3>{interview.title}</h3><div className="mi-card-meta"><span><Calendar size={13} /> {formatWhen(interview.scheduledAt)}</span><span><Users size={13} /> {interview.participantIds.length + 1} people</span><span className={`mi-status-pill mi-status-${interview.status.toLowerCase()}`}>{interview.status === "LIVE" ? "Live now" : interview.status.toLowerCase()}</span></div></div><div className="mi-card-actions"><button className="mi-btn-ghost mi-btn-small" onClick={async () => { try { await navigator.clipboard.writeText(link); setCopied(true); setTimeout(() => setCopied(false), 1800); } catch { setCopied(false); } }}><Link2 size={14} /> {copied ? "Copied!" : "Copy link"}</button>{interview.isHost && interview.status === "SCHEDULED" && <button className="mi-btn-ghost mi-btn-small" onClick={() => onCancel(interview)}>Cancel</button>}{(interview.status === "LIVE" || interview.status === "SCHEDULED") && <button className="mi-btn-primary mi-btn-small" disabled={!canJoin} onClick={() => onEnter(interview)}><Video size={14} /> {interview.status === "LIVE" ? "Join now" : "Enter room"}</button>}</div></article>; }

export default function MockInterviewsPage() { const navigate = useNavigate(); const [interviews, setInterviews] = useState(null); const [showSchedule, setShowSchedule] = useState(false); const [error, setError] = useState(""); const load = () => listMockInterviews().then(setInterviews).catch(() => setError("Could not load your mock interviews")); useEffect(() => { load(); const socket = getRealtimeSocket(); const refresh = () => load(); ["mock-interview:invited", "mock-interview:participant-joined", "mock-interview:status-updated", "mock-interview:ended", "mock-interview:cancelled"].forEach((event) => socket.on(event, refresh)); return () => ["mock-interview:invited", "mock-interview:participant-joined", "mock-interview:status-updated", "mock-interview:ended", "mock-interview:cancelled"].forEach((event) => socket.off(event, refresh)); }, []); const { upcoming, past } = useMemo(() => { const list = interviews || []; return { upcoming: list.filter((x) => !x.isPast), past: list.filter((x) => x.isPast) }; }, [interviews]); const cancel = async (x) => { if (!window.confirm(`Cancel "${x.title}"?`)) return; try { await cancelMockInterview(x.id); load(); } catch { setError("Could not cancel that interview"); } }; return <div className="mi-page"><div className="mi-page-header"><div><h1>Mock Interviews</h1><p>Schedule real-time mock interviews with peers — camera, mic, and screen share in the browser.</p></div><button className="mi-btn-primary" onClick={() => setShowSchedule(true)}><Plus size={16} /> Schedule interview</button></div>{error && <div className="mi-error">{error}</div>}{interviews === null ? <div className="mi-empty">Loading…</div> : interviews.length === 0 ? <div className="mi-empty"><Video size={28} /><strong>No interviews scheduled yet</strong><span>Schedule one with a peer, or share the link after creating.</span></div> : <>{[ ["Upcoming", upcoming], ["Past", past] ].map(([label, list]) => list.length > 0 && <section className="mi-section" key={label}><h2>{label}</h2><div className="mi-list">{list.map((x) => <InterviewCard key={x.id} interview={x} onCancel={cancel} onEnter={(item) => navigate(`/dashboard/mock/${item.id}`)} />)}</div></section>)}</>}{showSchedule && <ScheduleModal onClose={() => setShowSchedule(false)} onCreated={() => { setShowSchedule(false); load(); }} />}</div>; }
