import { useEffect, useRef, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { Track } from "livekit-client";
import { Camera, CameraOff, Copy, LogOut, Mic, MicOff, MonitorUp, MonitorX, PhoneOff, Users } from "lucide-react";
import { endMockInterviewForEveryone, joinMockInterviewCall, leaveMockInterviewCall, toggleMockInterviewCamera, toggleMockInterviewMic, toggleMockInterviewScreenShare, useMockInterviewCall } from "./api";
import "./mockInterviews.css";

const clock = (seconds) => `${Math.floor(seconds / 60).toString().padStart(2, "0")}:${(seconds % 60).toString().padStart(2, "0")}`;

export default function MockInterviewRoom() {
  const { interviewId } = useParams(); const navigate = useNavigate(); const call = useMockInterviewCall(); const [copied, setCopied] = useState(false);
  useEffect(() => { if (call.interviewId !== interviewId) joinMockInterviewCall(interviewId); }, [call.interviewId, interviewId]);
  const { interview, room, tracks, micEnabled, cameraEnabled, screenSharing, status, error, remaining } = call;
  const leave = () => { leaveMockInterviewCall(); navigate("/dashboard/mock"); };
  const endForEveryone = async () => { if (!window.confirm("End this interview for everyone?")) return; await endMockInterviewForEveryone(interviewId); navigate("/dashboard/mock"); };
  const copyLink = async () => { if (!interview) return; try { await navigator.clipboard.writeText(`${window.location.origin}/dashboard/mock/join/${interview.joinCode}`); setCopied(true); setTimeout(() => setCopied(false), 1800); } catch { setCopied(false); } };
  const screen = tracks.find((x) => x.source === Track.Source.ScreenShare && x.track.kind === Track.Kind.Video); const cameras = tracks.filter((x) => x.source !== Track.Source.ScreenShare && x.track.kind === Track.Kind.Video); const audios = tracks.filter((x) => x.track.kind === Track.Kind.Audio); const participantCount = new Set(cameras.map((x) => x.participant.sid)).size || 1; const statusLabel = status === "connecting" ? "Connecting…" : status === "connected" ? "Connected" : status === "ended" ? "Call ended" : status === "error" ? "Unable to connect" : "Connecting…";
  return <div className="mi-room"><header className="mi-room-header"><div><span className="mi-room-eyebrow">Mock interview</span><h2>{interview?.title || "Loading…"}</h2><small>{statusLabel}{remaining !== null && ` · ${clock(remaining)} remaining`}</small></div><div className="mi-room-header-actions"><button className="mi-btn-ghost mi-btn-small" onClick={copyLink}><Copy size={14} /> {copied ? "Copied!" : "Invite link"}</button><span className="mi-room-count"><Users size={14} /> {participantCount}</span></div></header>{error ? <div className="mi-error mi-room-error">{error}</div> : <div className="mi-room-body">{audios.map((x) => <AudioTrack key={x.sid} item={x} />)}{screen && <div className="mi-screenshare-tile"><RoomTrack item={screen} /></div>}<div className={screen ? "mi-grid mi-grid-strip" : "mi-grid"}>{cameras.length ? cameras.map((x) => <RoomTrack key={x.sid} item={x} showLabel />) : <div className="mi-empty-tile"><strong>{statusLabel}</strong><span>Allow camera and microphone access when your browser asks.</span></div>}</div></div>}<footer className="mi-room-controls"><button className={micEnabled ? "mi-control" : "mi-control off"} onClick={toggleMockInterviewMic} disabled={!room}>{micEnabled ? <Mic size={17} /> : <MicOff size={17} />}<span>{micEnabled ? "Mute" : "Unmute"}</span></button><button className={cameraEnabled ? "mi-control" : "mi-control off"} onClick={toggleMockInterviewCamera} disabled={!room}>{cameraEnabled ? <Camera size={17} /> : <CameraOff size={17} />}<span>{cameraEnabled ? "Stop video" : "Start video"}</span></button><button className={screenSharing ? "mi-control active" : "mi-control"} onClick={toggleMockInterviewScreenShare} disabled={!room}>{screenSharing ? <MonitorX size={17} /> : <MonitorUp size={17} />}<span>{screenSharing ? "Stop sharing" : "Share screen"}</span></button><button className="mi-control leave" onClick={leave}><LogOut size={17} /><span>Leave</span></button>{interview?.isHost && <button className="mi-control end" onClick={endForEveryone}><PhoneOff size={17} /><span>End for everyone</span></button>}</footer></div>;
}

function RoomTrack({ item, showLabel }) { const elementRef = useRef(null); useEffect(() => { const element = elementRef.current; if (!element) return undefined; item.track.attach(element); return () => item.track.detach(element); }, [item.track]); return <div className="mi-tile"><video ref={elementRef} autoPlay playsInline muted={item.participant.isLocal} />{showLabel && <span className="mi-tile-label">{item.participant.name || "Participant"}{item.participant.isLocal ? " (you)" : ""}</span>}</div>; }
function AudioTrack({ item }) { const elementRef = useRef(null); useEffect(() => { const element = elementRef.current; if (!element) return undefined; item.track.attach(element); return () => item.track.detach(element); }, [item.track]); return <audio ref={elementRef} autoPlay muted={item.participant.isLocal} />; }
